# fly.toml app configuration file generated for winter-bush-2674 on 2023-06-28T02:50:41-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "winter-bush-2674"
primary_region = "lax"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
